name: web
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: casperdcl/jupyterlite-xeus-pages@v1
      with:
        environment-file: environment.yml
  deploy:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/v')
    permissions: {pages: write, id-token: write}
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    needs: build
    runs-on: ubuntu-slim
    steps:
    - id: deploy
      uses: actions/deploy-pages@v5
